server:
  port: 9000
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: movie-mashup-route
          uri: lb://MOVIE-MASHUP
          predicates:
            - Path=/movie-mashup
          filters:
            - RewritePath=/movie-mashup, /top-recommendations
management:
  endpoints:
    web:
      exposure:
        include: "*"
