server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
movie-rater-service:
  base-url: http://MOVIE-RATER/rating
movie-recommender-service:
  base-url: http://MOVIE-RECOMMENDER/recommend